### ISSUE TITLE
Create a song chart tutorial for artists

### ISSUE THREAD

**Issue by Pant0don** [Skittluier/Kickblips_2#26]

**Comment by Skittluier** [comment]
These are the current rules for creating a Midi track:

1. There should be at least 2 tracks.
2. Track 0 should stay empty, we work from Track 1.
3. Every track from Track 1 should contain Midi Events.
4. The original artist's name should be in the "Track Name" text event in Track 1.
5. Every track from Track 1 should have a Meta Event Type in the Midi Events which decides the Tempo of the track. (in BPM)
