### ISSUE TITLE
BPM does not get set correctly

### ISSUE THREAD

**Issue by Pant0don** [Skittluier/Kickblips_2#30]
BPM is not getting set correctly? innitial value for BPM is 125 in code, when playing Punk Rock Girl (which is 130bpm and has this data in its midi file) the notes are too slow. Setting the default value for BPM to 130 makes the notes line up correctly

**Comment by Skittluier** [comment]
It seems the MetaEventType.Tempo is not being set. This decides the BPM within the track. We need a new Punk Rock Girl track to re-evaluate it. @Pant0don
